name: Get MacOS SDK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      # - uses: actions/checkout@v4

      - name: Package MacOSX13.0.sdk
        run: |
          set -eux
          SDK_PATH="/Applications/Xcode_14.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk"
          for f in $SDK_PATH/usr/lib/*.tbd; do
            dylib=$(sed -n "s/.*install-name:[[:space:]]*'\([^']*\)'.*/\1/p" "$f")
            if [ -n "$dylib" ] && [ -f "$dylib" ]; then
              echo "Copying $dylib"
              cp -RL "$dylib" $SDK_PATH/
            fi
          done
          tar -cJhf MacOSX13.0.sdk.tar.xz -C "$(dirname "$SDK_PATH")" "$(basename "$SDK_PATH")"
          ls -lh MacOSX13.0.sdk.tar.xz

      - uses: actions/upload-artifact@v4
        with:
          name: MacOSX13.0.sdk
          path: MacOSX13.0.sdk.tar.xz
