name: OSXCross Compiler

on:
  workflow_dispatch:

env:
  MACOS_SDK_VERSION: 13.0

jobs:
  build-cross-compiler:
    name: Build Cross Compiler
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare For Build
        run: |
          GITHUB_REPOSITORY=${{ github.repository }}
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >>"$GITHUB_ENV"
          # shellcheck disable=SC2129
          echo "OUT_TARBALL_PATH=$PWD/${GITHUB_REPOSITORY##*/}.tar.xz" >>"$GITHUB_ENV"
        shell: bash

      - name: Build
        run: |
          cat <<'EOF' >"$PWD/action-ci-build.sh"
          OSX_CROSS_COMPILER="/workspace/${GITHUB_REPOSITORY##*/}"
          cd "$OSX_CROSS_COMPILER" || exit
          # picked this version as they work well with godot-rust, feel free to change
          # git checkout 7c090bd8cd4ad28cf332f1d02267630d8f333c19

          UNATTENDED=yes OSX_VERSION_MIN=10.10 CLANG_VERSION=14.0.0 ./build.sh

          cd "$OSX_CROSS_COMPILER" || exit
          mv target "${GITHUB_REPOSITORY##*/}"
          tar -cJf "${GITHUB_REPOSITORY##*/}.tar.xz" "${GITHUB_REPOSITORY##*/}"
          EOF

          exec docker run -v "$PWD:/workspace/${GITHUB_REPOSITORY##*/}" \
              -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
              -e MACOS_SDK_VERSION=$MACOS_SDK_VERSION \
              --entrypoint=bash "ghcr.io/lcjuves/osx-cross-compiler-builder" -ex "/workspace/${GITHUB_REPOSITORY##*/}/action-ci-build.sh"
        shell: bash

      - name: Publish Artifact
        uses: softprops/action-gh-release@v1
        with:
          name: OSX Cross Compiler
          tag_name: osx-cross-compiler
          prerelease: false
          files: |
            ${{ env.OUT_TARBALL_PATH }}
